import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "../components/NavbarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "PRICESPARK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          margin: 0,
          padding: 0,
          backgroundColor: "#ffffff",
        }}
      >
        <div style={styles.wrapper}>
          <NavbarWrapper />
          <main style={styles.main}>{children}</main>
          <footer style={styles.footer}>© Copyright by Clueless</footer>
        </div>
      </body>
    </html>
  );
}

const styles = {
  wrapper: {
    position: "relative",
    width: "100%",
    height: "100vh",
  },
  main: {
    position: "absolute",
    top: "7vh",
    left: 0,
    right: 0,
    height: "83vh",
    overflowY: "auto",
    padding: "20px",
    boxSizing: "border-box",
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "10vh",
    backgroundColor: "#0070f3",
    color: "white",
    textAlign: "center",
    lineHeight: "10vh",
    fontFamily: "Arial",
    fontSize: "14px",
  },
};